spring.application.name=demo
server.port=8080

# The DB_URL, DB_USER, and DB_PASSWORD will be set in Render's dashboard
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/traffic}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:password}

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
